Translated Descriptions
CheckIO-to-German/Digit-Doublets pull request #2
Opened 2016-10-11 20:35 UTC by DahliaSR

2016-10-13 01:41 UTC, GiForce commented on translations/de/info/task_description.html
> +            Aus dem Englischen von Jörg Karau, 2008
that's great...\*\*starts a google-search\*\*  congrats for discovering joergkarau-texte.de! 👾

2016-10-13 01:49 UTC, GiForce commented on translations/de/info/task_description.html
> +    Gegeben wird eine Liste von Zahlen gleicher Länge. Die erste und letzte Zahl bilden
Gegeben ist...

2016-10-13 01:57 UTC, GiForce commented on translations/de/info/task_description.html
> +    der Liste die kürzeste, gültige Kette zu bilden.
_die kürzest gültige Kette_ should it be.

2016-10-13 02:00 UTC, GiForce commented on translations/de/info/task_description.html
> +    Die kürzeste, gültige Kette von der ersten (123) bis zur letzten Zahl (999) ist:
I still think _die kürzest gültige Kette_

2016-10-13 03:02 UTC, GiForce commented on translations/de/info/task_description.html
> +    <strong>Ausgabe: </strong> Die kürzeste, gültige Kette von der ersten bis zur letzten Zahl als Liste.
déjà vu!  what's in for _die kürzest mögliche Kette_ ?

2016-10-13 03:16 UTC, GiForce commented on translations/de/info/task_description.html
> +    Diese Aufgabe ist eine Variante des <a href="https://de.wikipedia.org/wiki/Pathfinding">Pathfinding<a> für Zahlen.
Although it is interesting, I still don't see the optimizing part in this mission. The list given already has a given length? At least in the example.  You can't shorten the list, can you? I'm confused. Nevertheless I like that linked wikipedia here, even it goes much further than this mission. I'd prefer the original's point, which links the representation of numbers and math to words. And that what's happening in this mission so far I get it. But maybe I just don't ¯\_(ツ)_/¯

But maybe I just don'

2016-10-13 03:21 UTC, GiForce requested changes
Maybe you'll notice, "die kürzeste, gültige Kette" should be optimized. Please.

2016-10-13 19:09 UTC, DahliaSR commented on translations/de/info/task_description.html
> +            Aus dem Englischen von Jörg Karau, 2008
Took me a while!

2016-10-13 19:10 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    Gegeben wird eine Liste von Zahlen gleicher Länge. Die erste und letzte Zahl bilden
:white_check_mark:

2016-10-13 19:20 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    Diese Aufgabe ist eine Variante des <a href="https://de.wikipedia.org/wiki/Pathfinding">Pathfinding<a> für Zahlen.
Not all the numbers in the given list are part of the correct chain: 
**Input:** [123, 991, 323, 321, 329, 121, 921, 125, 999] 
**Result:** [123, 121, 921, 991, 999]  

Actually, there are no words which are represented as numbers in this task, it only replaced words by numbers. But these numbers are not representing words... So I removed that sentence as it seems to be a bit confusing.

2016-10-13 19:23 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    der Liste die kürzeste, gültige Kette zu bilden.
:white_check_mark:

2016-10-13 19:23 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    Die kürzeste, gültige Kette von der ersten (123) bis zur letzten Zahl (999) ist:
:white_check_mark:

2016-10-13 19:24 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    <strong>Ausgabe: </strong> Die kürzeste, gültige Kette von der ersten bis zur letzten Zahl als Liste.
:white_check_mark:

2016-10-14 18:43 UTC, GiForce commented
😳 really, didn’t see that, maybe I was comparing the german list with the english one when validating my argument. I should start to look at the files when formatted. There is no way github interprets HTML directly? 
> 
> Not all the numbers in the given list are part of the correct chain: 
> Input: [123, 991, 323, 321, 329, 121, 921, 125, 999] 
> Result: [123, 121, 921, 991, 999]
>

2016-10-14 18:52 UTC, DahliaSR commented
Nope there's not, thats why I'm doing it in a local repo on my computrer.

> really, didn’t see that, maybe I was comparing the german list with the english one when validating my argument. I should start to look at the files when formatted. There is no way github interprets HTML directly?

2016-10-17 02:59 UTC, GiForce approved these changes
✅

2016-10-17 18:21 UTC, merged